// Objective-C API for talking to git.torproject.org/pluggable-transports/obfs4.git/obfs4proxy Go package.
//   gobind -lang=objc -prefix=Go git.torproject.org/pluggable-transports/obfs4.git/obfs4proxy
//
// File is generated by gobind. Do not edit.

#ifndef __GoIobfs4proxy_H__
#define __GoIobfs4proxy_H__

@import Foundation;
#include "GoUniverse.h"


FOUNDATION_EXPORT void GoIobfs4proxyMain();

#endif
