line_length:
  - 245
  - 250

disabled_rules:  
  - identifier_name
  - type_body_length
  - function_body_length
  - force_cast
  - type_name
  - large_tuple
  - file_length
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - function_parameter_count
  - todo
  - nesting
excluded:
  - Pods
  - UnitTests