line_length: # Target: 120/200
  - 230
  - 250

type_body_length: # Target: 250/350
  - 380
  - 400

function_body_length: # Target: 50/100
  - 90
  - 100

file_length: # Target: 400/1000
  - 675
  - 1000

disabled_rules:  
  - identifier_name
  - multiple_closures_with_trailing_closure
  - function_parameter_count
  - todo
  - opening_brace # False positives on regex

excluded:
  - Pods
  - UnitTests
  # Files scheduled for refactor
  - ./**/SettingsViewController.swift
  - ./**/AddAmountViewController.swift
  - ./**/EmojiIdView.swift
  - ./**/AnimatedBalanceLabel.swift