disabled_rules:
  - line_length
  - identifier_name
  - type_body_length
  - function_body_length
  - force_try
  - force_cast
  - shorthand_operator
  - type_name
  - large_tuple
  - file_length
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - function_parameter_count
  - todo
  - nesting
excluded:
  - Pods