
// Objective-C API for talking to the following Go packages
//
//	git.torproject.org/pluggable-transports/obfs4.git/obfs4proxy
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Iobfs4proxy_H__
#define __Iobfs4proxy_H__

#include "GoIobfs4proxy.h"
#include "GoUniverse.h"

#endif
