default_platform(:ios)

platform :ios do
  lane :dsym do |options|
    sentry_upload_dsym(
      auth_token: options[:auth_token],
      org_slug: options[:org_slug],
      project_slug: options[:project_slug],
      dsym_path: options[:dsym_path]
    )
    skip_docs()
  end
end
